# Generated by Django 4.0.1 on 2022-01-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('opis', models.TextField(max_length=1000)),
                ('obraz', models.ImageField(upload_to='Films')),
                ('kategoria', models.CharField(choices=[('A', 'AKCJA'), ('D', 'DRAMAT'), ('K', 'KOMEDIA'), ('R', 'ROMANS')], max_length=1)),
                ('jezyk', models.CharField(choices=[('PL', 'POLSKI'), ('EN', 'ENGLISH')], max_length=2)),
                ('status', models.CharField(choices=[('ND', 'NIEDAWNO DODANE'), ('NO', 'NAJCZĘŚCIEJ OGLĄDANE'), ('TR', 'NAJLEPIEJ OCENIANE')], max_length=2)),
                ('rok_produkcji', models.IntegerField(default=0)),
                ('wyswietlenia', models.IntegerField(default=0)),
            ],
        ),
    ]
