# Generated by Django 4.0.1 on 2022-01-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strona_kino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul_filmu', models.CharField(max_length=200)),
                ('id_filmu', models.TextField()),
                ('cena_biletu', models.TextField()),
                ('ocena', models.TextField()),
                ('opis', models.CharField(max_length=500)),
            ],
        ),
    ]
