# Generated by Django 4.0.1 on 2022-01-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strona_kino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_biletu', models.CharField(choices=[('N', 'NORMALNY'), ('U', 'ULGOWY'), ('R', 'RODZINNY')], max_length=10)),
                ('cena_biletu', models.IntegerField(default=0)),
                ('ilosc_biletow', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='obraz',
            field=models.ImageField(upload_to='Strona_kino'),
        ),
    ]
